import os
os.system("clear") 
print("Sistema de criptografia by Nexamos")
print("Seja bem vindo Sr. L.S") 
print("Aqueles que buscam se aventuram")
while True:
    frases = input("Criptografar: ")
    for x in frases:
        frases = frases.replace('a', 'z261')
        frases = frases.replace('b', 'y252')
        frases = frases.replace('c', 'x243')
        frases = frases.replace('d', 'w234')
        frases = frases.replace('e', 'v225')
        frases = frases.replace('f', 'u216')
        frases = frases.replace('g', 't207')
        frases = frases.replace('d', 'w234')
        frases = frases.replace('h' ,  's198')
        frases = frases.replace('i' ,  'r189')
        frases = frases.replace('j' ,  'q1710')
        frases = frases.replace('k' ,  'p1611')
        frases = frases.replace('l ',  'o1512')
        frases = frases.replace('m' ,  'n1413')
        frases = frases.replace('n' ,  'm1313')
        frases = frases.replace('o' ,  'l1212')
        frases = frases.replace('p',  'k1111')
        frases = frases.replace('q ',  'j1010')
        frases = frases.replace('r' ,  'i919')
        frases = frases.replace('s' ,  'h820')
        frases = frases.replace('t' ,  'g721')
        frases = frases.replace('u',  'f622')
        frases = frases.replace('v ',  'e522')
        frases = frases.replace('w ',  'd423')
        frases = frases.replace('x' ,  'c324')
        frases = frases.replace('y ',  'b225')
        frases = frases.replace('z ',  'a126')
        conclui = frases.strip()
        print(conclui)
        break 
    
        
